import React from 'react'

const MidTEXT = () => {
  return (
    <section className='flex flex-row  pt-10 pl-5  text-xl '>
    <div className=' w-56  mr-3 text-xl '>About Us</div>
    <div className=' w-midImg pr-20  text-4xl text-justify text-black'> We craft innovative interior solutions that combine minimalist design with modern functionality, ideal for enhancing contemporary living and commercial spaces.</div>
    <div className=' w-mid h-48 flex justify-end pl-4 '>
    <img  src="/img/plano.svg" alt="" />
  </div>
  <div className=' w-56  mr-3'></div>
</section>
  )
}

export default MidTEXT